### ISSUE TITLE
Merge pull request 121 please

### ISSUE THREAD

**Issue by jcowey** [papyri/idp.data#122]
May I please ask you, Hugh, to deal with the pull request:

https://github.com/papyri/idp.data/pull/121

The reason I ask you is that it has to do with new Biblio data. The last time I processed a pull request for biblio we landed in the mess that presented itself just before Christmas. 

There are not many new files, so it will not be a case of starting a new 1000er folder. What makes me uneasy is that travis is complaining and "All checks have failed" is the message.

Looking at one of them
https://travis-ci.org/papyri/idp.data/builds/634175409
specifically
https://travis-ci.org/papyri/idp.data/jobs/634175411?utm_medium=notification&utm_source=github_status

I think that
`/home/travis/build/papyri/idp.data/epidoc/8.13/tei-epidoc.rng:1:1: fatal: Premature end of file.`
probably indicates that the individual biblio files do not validate. They are snippets or whatever that is called technically. I suspect that there is some internal work around that allows the editor to process such files into master, but is a stumbling block when committed via pull or directly to master.

Could that be causing problems.

Anyway it would be great if you would merge the pull request so that the data is in master and available.

**Comment by Edelweiss** [comment]
I added a few more changes today, please @jcowey, review again before the merge

https://github.com/papyri/idp.data/commits/bibliographie_papyrologique

**Comment by jcowey** [comment]
Now done
