### ISSUE TITLE
Not accessing translation

### ISSUE THREAD

**Issue by rla2118** [papyri/idp.data#15]
I cannot access translations on my dashboard, http://www.papyri.info/editor/user/board_dashboard?board_id=3

I just get this error message

"We're sorry, but something went wrong.

We've been notified about this issue and we'll take a look at it shortly.

You should be redirected momentarily."

**Comment by jcowey** [comment]
Closing this as I have opened it in .../papyri/sosol as an issue

https://github.com/papyri/sosol/issues/1

Have alerted ryanfb
