### ISSUE TITLE
First line of the papyrus is not well tagged in: o.abu.mina.396…

### ISSUE THREAD

**Issue by danielrruf** [papyri/idp.data#150]
o.abu.mina.396

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/o.abu.mina/o.abu.mina.396.xml#L52

**Comment by jcowey** [comment]
Fixed by:
https://github.com/papyri/idp.data/commit/1426458c5891ee40bd565d1fb89751bb13551a54
