### ISSUE TITLE
First linenumber not correctly tagged in o.cret.chers.57

### ISSUE THREAD

**Issue by danielrruf** [papyri/idp.data#152]
The first line is not correctly tagged in o.cret.chers.57

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/blob/master/DDB_EpiDoc_XML/o.cret.chers/o.cret.chers.57.xml#L52

**Comment by jcowey** [comment]
Fixed by:
https://github.com/papyri/idp.data/commit/ea2e65fe39b1d9179cfa4f38e0bcebf4b92fbf7f
