### ISSUE TITLE
idno changes for p.bas

### ISSUE THREAD

**Issue by jcowey** [papyri/idp.data#214]
Many files from 
https://github.com/papyri/idp.data/tree/master/DDB_EpiDoc_XML/p.bas
have been reprinted in 
https://github.com/papyri/idp.data/tree/master/DDB_EpiDoc_XML/p.bas/p.bas.2

Any files (mostly dummy headers pointing to the p.bas;2;_ equivalent) in 
https://github.com/papyri/idp.data/tree/master/DDB_EpiDoc_XML/p.bas
should be part of 
https://github.com/papyri/idp.data/tree/master/DDB_EpiDoc_XML/p.bas(p.bas.1

with all relevant changes in DDb and HGV (probably less affected than by p.giss)

This requires action very similar to #156.

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/pull/215

This should now be solved by:
https://github.com/papyri/idp.data/commit/2b0b686437b40eac9ce7c4ef1b6023a8c59dc22a

**Comment by samosafuz** [comment]
This is now indexed properly.
