### ISSUE TITLE
Please merge a biblio commit to master biblio

### ISSUE THREAD

**Issue by jcowey** [papyri/idp.data#23]
Arising from the decisions made in the following two issues:
https://github.com/DCLP/dclpxsltbox/issues/170
https://github.com/DCLP/dclpxsltbox/issues/171

the following commit:
https://github.com/papyri/idp.data/commit/ac7d0672131c7971d4619edcc8f901dea49e279d
did not make it to 
https://github.com/papyri/idp.data/tree/master/Biblio

I am not sure why and it does not really matter why, but would you please now merge the commit into ../master/Biblio

https://github.com/papyri/idp.data/blob/ac7d0672131c7971d4619edcc8f901dea49e279d/Biblio/80/79621.xml#L7

is better than

https://github.com/papyri/idp.data/blob/master/Biblio/80/79621.xml#L7

Many thanks

**Comment by hcayless** [comment]
Done.
