### ISSUE TITLE
Search error with #

### ISSUE THREAD

**Issue by wgclaytor** [papyri/idp.data#286]
Searching for #???εμ° (vel sim.) is returning many false positives: https://papyri.info/search?STRING1=%23%3F%3F%3F%CE%B5%CE%BC%C2%B0&target1=TEXT&no_caps1=on&no_marks1=on

**Comment by samosafuz** [comment]
I noticed something similar [a while back](https://github.com/papyri/navigator/issues/124), which Hugh took a look at and attempted a fix. In that ticket, you'll see he explains a bit about what's going on underneath the hood and why it's not so straightforward. 

This is all to say that it's been noticed before; by keeping your ticket open we'll signal that there's still a need for refinement.

**Comment by hcayless** [comment]
I think this one's actually working now.

**Comment by wgclaytor** [comment]
Thanks, Hugh and Mike. I tried to search for #???εμ° again and received 399
hits (should've recorded the number earlier), but many of them are still
false positives. A common cause of the false positive result seems to be
when the previous word is abbreviated, e.g. καλά(μων) δέμ(ατα).
