### ISSUE TITLE
Double origPlace elements

### ISSUE THREAD

**Issue by enury** [papyri/idp.data#396]
I have found 57 documents that have two `<origPlace>`, which look like a mistake. All of them have the same two :

```
<origPlace>Fundort: Ta Memnoneia (Hermonthites)</origPlace>
<origPlace>Ta Memnoneia (Egypt)</origPlace>
```

For example: TM [783347](https://papyri.info/ddbdp/jjp;47;49_12). 

I would suggest to correct it to `<origPlace>Ta Memnoneia (Hermonthites)</origPlace>`.

It is my impression that the "Fundort" is indicated usually only when there is a distinction to be made with another place (Schreibort, Zielort etc), is that correct? Should the `<provenance>` keep the type "found", or have a generic "located" instead?

**Comment by jcowey** [comment]
Yes, please change throughout to `<origPlace>Ta Memnoneia (Hermonthites)</origPlace>` and make sure that it is
`<provenance type="located">` instead of `<provenance type="found">`
