### ISSUE TITLE
provenance of type "written"

### ISSUE THREAD

**Issue by enury** [papyri/idp.data#397]
15 documents with a `<provenance type="written">` but "written" is not a valid type according to the formular in the Editor.

Should that be corrected to "composed" ?

Ex: TM [873586](https://papyri.info/ddbdp/p.yale;4;146).

**Comment by jcowey** [comment]
Yes, please replace "written" to "composed".

**Comment by jcowey** [comment]
This is now done. Thank you.

**Comment by Xennis** [comment]
FYI @enury and @jcowey : There is one more: https://github.com/papyri/idp.data/blob/c258522d8ae0956fdf22bd4602f3cc9771f24b6f/DCLP/698/697546.xml#L40

That seems to be the only being left:

```shell
$ git grep '<provenance type="written">'
DCLP/698/697546.xml:                        <provenance type="written">
```
