### ISSUE TITLE
BGU 7.1676

### ISSUE THREAD

**Issue by danielrruf** [papyri/idp.data#40]
` <lb n="14"/>θελήσῃς μὴ <choice><reg>ἀναβῆναι</reg><orig>ἀναβῆ<lb n="13" break="no"/>νε</orig></choice>, πέμψου
`

should be

` <lb n="14"/>θελήσῃς μὴ <choice><reg>ἀναβῆναι</reg><orig>ἀναβῆ<lb n="14" break="no"/>νε</orig></choice>, πέμψου
`

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/commit/d2495304d6a1385a8c8c1148e384c3c51e31e823

fixes this.

`<lb n="13" break="no"/>` was wrong in line 14. No break at all.
