### ISSUE TITLE
p.cair.zen.1.59025 ln. 2

### ISSUE THREAD

**Issue by danielrruf** [papyri/idp.data#42]
Something wrong in:

`<lb n="2"/>χαίρε<unclear>ι</unclear>ν. <choice><reg>χρείαν</reg><orig>χρέ<lb n="23" break="no"/>αν</orig></choice>`

prob. it's either `<lb n="3" break="no"/>` or no line break at all

**Comment by jcowey** [comment]
lb in line 2 is incorrect. Fixed by 

https://github.com/papyri/idp.data/commit/2e00d040c3833e5552940db9ee7a77ef1b0129a3
