### ISSUE TITLE
p.oxy.56.3852 l.18, p.oxy.59.3993 l.12, 15, 18, 23

### ISSUE THREAD

**Issue by danielrruf** [papyri/idp.data#52]
Same case (parasitic medial lb) as POxy.48.3400 in p.oxy.56.3852 l.18
`<lb n="18" break="no"/>ουσία ἔσ<unclear>τα</unclear>ι <choice><reg>ἡμῖν</reg><orig>ἡ<lb n="21" break="no"/>μεῖν</orig></choice> <choice><reg>ἐπαφρό`

and p.oxy.59.3993 in:
`<lb n="12"/>ἐδηλώσατε <choice><reg>ἡμῖν</reg><orig>ἡ<lb n="17" break="no"/>μεῖν</orig></choice> λαβεῖν ἡμᾶς παρὰ Πετοσεί`

and 15:
`<lb n="15"/>γὰρ <choice><reg>ἡμῖν</reg><orig>ἡ<lb n="17" break="no"/>μεῖν</orig></choice> ὅτι, σ<unclear>υ</unclear>λλέγομεν αὐτά. ἔλεγον γὰρ ὅτι,`
and again in l. 18

`<lb n="18" break="no"/>μῶν τὰς <expan><ex>δραχμὰς</ex></expan> <num value="500">φ</num> καὶ <choice><reg>ἡμῖν</reg><orig>ἡ<lb n="17" break="no"/>μεῖν</orig></choice> τὸ γράμμα δοῦναι. αὐ`

and 23:

`<lb n="23"/>μέχρ<supplied reason="lost">ι</supplied> οὗ δηλώσεις <choice><reg>ἡμῖν</reg><orig><supplied reason="lost">ἡ</supplied>μεῖν</orig></choice>. ἔγραψας <choice><reg>ἡμῖν</reg><orig>ἡ<lb n="17" break="no"/>μεῖν</orig></choice>,`

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/commit/6c591955a0712551288ef104127f1fe2f7ec5df1

fixes p.oxy.59.3993

**Comment by jcowey** [comment]
https://github.com/papyri/idp.data/commit/f381b24bf8bffadf01ce8e471473021cbf9de50e

fixes p.oxy.56.3852
