### ISSUE TITLE
p.oxy.62.4340 l. 24; p.oxy.7.1068 l. 25; p.oxy.7.1069 l.18

### ISSUE THREAD

**Issue by danielrruf** [papyri/idp.data#54]
seemingly parasitic medial lb in 

p.oxy.62.4340 `<lb n="24" break="no"/>κα καὶ <choice><reg>σεσημείωμαι</reg><orig>σεσειμίωμε</orig></choice> <expan><ex>δραχμὰς</ex></expan> .<lb n="2"/>ὁ Σόεις`

In p.oxy.7.1068

`<lb n="25" break="no"/>δεὶς</reg><orig>μη<lb n="11" break="no"/>δὶς</orig></choice> <choice><reg>ἐνοχλήσει</reg><orig>ἐνοχλήσι</orig></choice> αὐτοῖς καθʼ ὁδόν,`

medial `<lb n="11" break="no"/>` seems to stand for `<lb n="25" break="no"/>`

in p.oxy.7.1069 l.18

`<lb n="18"/>καὶ <choice><reg>πέμψαι</reg><orig>πέμ<lb n="14" break="no"/>ψε</orig></choice> <choice><reg>πρὸς</reg><orig>πρὸ</orig></choice> <choice><reg>σέ</reg><orig>σεν</orig></choice>. τὴν`

medial lb seems superfluous

**Comment by samosafuz** [comment]
It took a while, but these are now fixed. Thanks for noticing them!
