### ISSUE TITLE
BGU 3.845 l. 7

### ISSUE THREAD

**Issue by danielrruf** [papyri/idp.data#66]
`<lb n="7"/>εὐχόμενός <choice><reg>σε</reg><orig>σαι</orig></choice> <choice><reg>ὑγιαίνειν</reg><orig><hi rend="diaeresis">ὑ</hi>γει<lb n="4" break="no"/>αίνιν</orig></choice>. πρῶτον 
`

`<lb n="4" break="no"/>` is either wrong or entirely omissible

**Comment by jcowey** [comment]
Corrected by https://github.com/papyri/idp.data/commit/b2bc0012dd666548c568d197e2d66a3792562a69
