### ISSUE TITLE
lb in p.abinn.43 l.9

### ISSUE THREAD

**Issue by danielrruf** [papyri/idp.data#72]
There's probably an error in `<lb n="9"/>τι <choice><reg>ὀφείλε<supplied reason="lost">τ</supplied>ε</reg><orig>ὀφίλε<supplied reason="lost">τ</supplied>ε</orig></choice> ἀπὸ τοῦ λ<supplied reason="lost">ό</supplied>γου <choice><reg>φοινίκων</reg><orig>φυνί**<lb n="13" break="no"/>**κων</orig></choice>`

**Comment by jcowey** [comment]
Fixed by:
https://github.com/papyri/idp.data/commit/4a7aab1deac760da421f472ea7eaa41a7d8df238
