### ISSUE TITLE
lb in POxy.1.121 l. 4

### ISSUE THREAD

**Issue by danielrruf** [papyri/idp.data#74]
the indication of a split in l4 of POxy.1.121 `<lb n="19" break="no"/>` is confusing and likely to be deleted

`<lb n="4"/>δύο <num value="2"/> ἀκάνθων <choice><reg>ἵνα</reg><orig>εἵ<lb n="19" break="no"/>να</orig></choice> δώσω`

**Comment by jcowey** [comment]
Corrected by https://github.com/papyri/idp.data/commit/5109a6fde288f03e8d45f4116a22a3f91f25454a
