### ISSUE TITLE
Unwanted redirects

### ISSUE THREAD

**Issue by Frederic-P** [papyri/idp.data#88]
When going to papyri.info by clicking this link: [http://papyri.info/ddbdp/bgu;1;108](http://papyri.info/ddbdp/bgu;1;108)

I get to see the information for BGU 1 180 (TM28231) instead of BGU 1 108(TM8882).

**Comment by hcayless** [comment]
This is the result of a data entry error (probably a very old one). I've corrected it, and will check to make sure the two get disentangled properly after the change gets synced.

**Comment by hcayless** [comment]
They're disentangled now
